services:
  kafka:
    extends:
      file: docker-compose.yml
      service: kafka

  registry:
    extends:
      file: docker-compose.yml
      service: registry

  jaws:
    extends:
      file: docker-compose.yml
      service: jaws

  softioc:
    extends:
      file: docker-compose.yml
      service: softioc

  epics2kafka:
    extends:
      file: docker-compose.yml
      service: epics2kafka
    build:
      context: .
      dockerfile: Dockerfile
