services:
  kafka:
    extends:
      file: compose.yaml
      service: kafka

  registry:
    extends:
      file: compose.yaml
      service: registry

  cli:
    extends:
      file: compose.yaml
      service: cli

  softioc:
    extends:
      file: compose.yaml
      service: softioc

  epics2kafka:
    extends:
      file: compose.yaml
      service: epics2kafka
    build:
      context: .
      dockerfile: Dockerfile
