services:
  kafka:
    extends:
      file: deps.yaml
      service: kafka

  registry:
    extends:
      file: deps.yaml
      service: registry

  jaws:
    extends:
      file: deps.yaml
      service: jaws

  softioc:
    extends:
      file: deps.yaml
      service: softioc

  epics2kafka:
    hostname: epics2kafka
    container_name: epics2kafka
    depends_on:
      - kafka
      - softioc
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      MONITOR_CHANNELS: "channel1|alarm-activations|a|alarm1,channel2|alarm-activations|a|alarm2,channel3|alarm-activations|a|alarm3"
    volumes:
      - ./container/epics2kafka/initdb.d:/config