---
version: '3.8'

services:
  epics2kafka:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt
    volumes:
      - ./build/install:/kafka/connect/jaws-epics2kafka