---
version: '3.8'

services:
  softioc:
    image: slominskir/softioc:1.1.0
    tty: true
    stdin_open: true
    hostname: softioc
    container_name: softioc
    ports:
      - "5064:5064/tcp"
      - "5065:5065/tcp"
      - "5064:5064/udp"
      - "5065:5065/udp"
    volumes:
      - ./examples/softioc-db:/db

  zookeeper:
    image: debezium/zookeeper:1.5.0.Final
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: debezium/kafka:1.5.0.Final
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CREATE_TOPICS: 'registered-alarms:1:1:compact,active-alarms:1:1:compact,shelved-alarms:1:1:compact'

  registry:
    image: confluentinc/cp-schema-registry:6.0.2
    hostname: registry
    container_name: registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: registry

  jaws:
    image: slominskir/jaws:2.7.1
    hostname: jaws
    container_name: jaws
    depends_on:
      - zookeeper
      - kafka
      - registry
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"

  epics2kafka:
    hostname: epics2kafka
    container_name: epics2kafka
    depends_on:
      - zookeeper
      - kafka
      - softioc
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      CONFIG_STORAGE_TOPIC: connect-configs
      OFFSET_STORAGE_TOPIC: connect-offsets
      STATUS_STORAGE_TOPIC: connect-status
      MONITOR_CHANNELS: "channel1|active-alarms|a|alarm1,channel2|active-alarms|a|alarm2,channel3|active-alarms|a|alarm3"
    volumes:
      - ./examples/connect-config:/config